### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by F4nX1ngCN** [Amemei/Amemei.github.io#1]
When I download the repo zip and setup the website on my server ,it is not working, I found the link is wrong.For example ,MaidLife is Amemei.github.io/MaidLife ,and i typed xxx.xxx/MaidLife/ in my browser. There is nothing in the catalogue, can you tell me how to setup this?

**Comment by SuSWhW** [comment]
游戏和网站存储库是分开的，你得把存储库也传了
