### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by TomIsFat** [Amemei/Amemei.github.io#7]
我想自己部署某个游戏的静态网页到服务器上，如何让存档存在服务器的文件目录里，而不是客户端的浏览器缓存里

**Comment by SuSWhW** [comment]
额😓，目前没有办法实现，因为网页版的rpgmacker游戏存档在rpgmacker设计之初就被设定为保存在缓存里

**Comment by TomIsFat** [comment]
> 额😓，目前没有办法实现，因为网页版的rpgmacker游戏存档在rpgmacker设计之初就被设定为保存在缓存里

感谢解答，还有一个问题，**有方法导出和导入存档吗？**

目前我知道的是电脑去浏览器控制台找本地存储的key-value对，安卓手机Chrome内核的浏览器就可以去data/data/应用包名/../*.ldb文件里面找，但是iOS的存档就没找到方法导出和导入

**Comment by SuSWhW** [comment]
> > 额😓，目前没有办法实现，因为网页版的rpgmacker游戏存档在rpgmacker设计之初就被设定为保存在缓存里
> 
> 感谢解答，还有一个问题，**有方法导出和导入存档吗？**
> 
> 目前我知道的是电脑去浏览器控制台找本地存储的key-value对，安卓手机Chrome内核的浏览器就可以去data/data/应用包名/../*.ldb文件里面找，但是iOS的存档就没找到方法导出和导入

应该也就只有你找到的那个方法了，rpgmacker没有给出浏览器游戏的存档导出方式
